### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m2-evaluacion-intermedia-laila25#1]
Really cool job @laila25  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number
- [x] `.form_btn2` class name is improvable.
### Advanced

- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

### JavaScript - Good practices

- [x] Move variables and constants declarations to the top of the file
- [x] Use `===` instead of `==` for comparisons

### Good practices

- [x] Remove commented code
- [x] Write your classes in English!
- [ ] Try to use imperative for your commit messages. Ex. - > Fix central text

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Hola @laila25, solo un comentario para que el código sea perfecto.

Solo ponemos funciones dentro de otras funciones cuando es estrictamente necesario. Aquí no lo sería https://github.com/Adalab/m2-evaluacion-intermedia-laila25/blob/master/js/main.js#L26.

Nos estás dejando flipados con el curro que estás haciendo últimamente. Enhorabuena señora, siéntete orgullosa.

**Comment by laila25** [comment]
Ok, lo revisaré.

Muchas gracias por el comentario 😄

La verdad es que le tenía mucho respeto a JS, y se me está dando mucho mejor de lo que esperaba!!
